package com.example.lfm.entity;

import java.io.Serializable;
import java.util.Date;

public class ActPrint implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.print_id
     *
     * @mbg.generated
     */
    private Long printId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.student_id
     *
     * @mbg.generated
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.user_print_id
     *
     * @mbg.generated
     */
    private Long userPrintId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.user_delivery_id
     *
     * @mbg.generated
     */
    private Long userDeliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.print_number
     *
     * @mbg.generated
     */
    private Integer printNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.both_side_flag
     *
     * @mbg.generated
     */
    private String bothSideFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.color_flag
     *
     * @mbg.generated
     */
    private String colorFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.sealing_flag
     *
     * @mbg.generated
     */
    private String sealingFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.cover_flag
     *
     * @mbg.generated
     */
    private String coverFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.paper_size
     *
     * @mbg.generated
     */
    private String paperSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.student_remark
     *
     * @mbg.generated
     */
    private String studentRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.address_id
     *
     * @mbg.generated
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.cover_color
     *
     * @mbg.generated
     */
    private String coverColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.fee
     *
     * @mbg.generated
     */
    private Double fee;

    private int pageNum;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.print_time
     *
     * @mbg.generated
     */
    private Date printTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.delivery_time
     *
     * @mbg.generated
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_print.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_print
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.print_id
     *
     * @return the value of act_print.print_id
     *
     * @mbg.generated
     */
    public Long getPrintId() {
        return printId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.print_id
     *
     * @param printId the value for act_print.print_id
     *
     * @mbg.generated
     */
    public void setPrintId(Long printId) {
        this.printId = printId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.student_id
     *
     * @return the value of act_print.student_id
     *
     * @mbg.generated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.student_id
     *
     * @param studentId the value for act_print.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.file_name
     *
     * @return the value of act_print.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    public int getPageNum() {
        return pageNum;
    }

    public void setPageNum(int pageNum) {
        this.pageNum = pageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.file_name
     *
     * @param fileName the value for act_print.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.file_url
     *
     * @return the value of act_print.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.file_url
     *
     * @param fileUrl the value for act_print.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.user_print_id
     *
     * @return the value of act_print.user_print_id
     *
     * @mbg.generated
     */
    public Long getUserPrintId() {
        return userPrintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.user_print_id
     *
     * @param userPrintId the value for act_print.user_print_id
     *
     * @mbg.generated
     */
    public void setUserPrintId(Long userPrintId) {
        this.userPrintId = userPrintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.user_delivery_id
     *
     * @return the value of act_print.user_delivery_id
     *
     * @mbg.generated
     */
    public Long getUserDeliveryId() {
        return userDeliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.user_delivery_id
     *
     * @param userDeliveryId the value for act_print.user_delivery_id
     *
     * @mbg.generated
     */
    public void setUserDeliveryId(Long userDeliveryId) {
        this.userDeliveryId = userDeliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.print_number
     *
     * @return the value of act_print.print_number
     *
     * @mbg.generated
     */
    public Integer getPrintNumber() {
        return printNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.print_number
     *
     * @param printNumber the value for act_print.print_number
     *
     * @mbg.generated
     */
    public void setPrintNumber(Integer printNumber) {
        this.printNumber = printNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.both_side_flag
     *
     * @return the value of act_print.both_side_flag
     *
     * @mbg.generated
     */
    public String getBothSideFlag() {
        return bothSideFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.both_side_flag
     *
     * @param bothSideFlag the value for act_print.both_side_flag
     *
     * @mbg.generated
     */
    public void setBothSideFlag(String bothSideFlag) {
        this.bothSideFlag = bothSideFlag == null ? null : bothSideFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.color_flag
     *
     * @return the value of act_print.color_flag
     *
     * @mbg.generated
     */
    public String getColorFlag() {
        return colorFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.color_flag
     *
     * @param colorFlag the value for act_print.color_flag
     *
     * @mbg.generated
     */
    public void setColorFlag(String colorFlag) {
        this.colorFlag = colorFlag == null ? null : colorFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.sealing_flag
     *
     * @return the value of act_print.sealing_flag
     *
     * @mbg.generated
     */
    public String getSealingFlag() {
        return sealingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.sealing_flag
     *
     * @param sealingFlag the value for act_print.sealing_flag
     *
     * @mbg.generated
     */
    public void setSealingFlag(String sealingFlag) {
        this.sealingFlag = sealingFlag == null ? null : sealingFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.cover_flag
     *
     * @return the value of act_print.cover_flag
     *
     * @mbg.generated
     */
    public String getCoverFlag() {
        return coverFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.cover_flag
     *
     * @param coverFlag the value for act_print.cover_flag
     *
     * @mbg.generated
     */
    public void setCoverFlag(String coverFlag) {
        this.coverFlag = coverFlag == null ? null : coverFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.paper_size
     *
     * @return the value of act_print.paper_size
     *
     * @mbg.generated
     */
    public String getPaperSize() {
        return paperSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.paper_size
     *
     * @param paperSize the value for act_print.paper_size
     *
     * @mbg.generated
     */
    public void setPaperSize(String paperSize) {
        this.paperSize = paperSize == null ? null : paperSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.student_remark
     *
     * @return the value of act_print.student_remark
     *
     * @mbg.generated
     */
    public String getStudentRemark() {
        return studentRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.student_remark
     *
     * @param studentRemark the value for act_print.student_remark
     *
     * @mbg.generated
     */
    public void setStudentRemark(String studentRemark) {
        this.studentRemark = studentRemark == null ? null : studentRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.status
     *
     * @return the value of act_print.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.status
     *
     * @param status the value for act_print.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.address_id
     *
     * @return the value of act_print.address_id
     *
     * @mbg.generated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.address_id
     *
     * @param addressId the value for act_print.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.cover_color
     *
     * @return the value of act_print.cover_color
     *
     * @mbg.generated
     */
    public String getCoverColor() {
        return coverColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.cover_color
     *
     * @param coverColor the value for act_print.cover_color
     *
     * @mbg.generated
     */
    public void setCoverColor(String coverColor) {
        this.coverColor = coverColor == null ? null : coverColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.fee
     *
     * @return the value of act_print.fee
     *
     * @mbg.generated
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.fee
     *
     * @param fee the value for act_print.fee
     *
     * @mbg.generated
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.pay_time
     *
     * @return the value of act_print.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.pay_time
     *
     * @param payTime the value for act_print.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.print_time
     *
     * @return the value of act_print.print_time
     *
     * @mbg.generated
     */
    public Date getPrintTime() {
        return printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.print_time
     *
     * @param printTime the value for act_print.print_time
     *
     * @mbg.generated
     */
    public void setPrintTime(Date printTime) {
        this.printTime = printTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.delivery_time
     *
     * @return the value of act_print.delivery_time
     *
     * @mbg.generated
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.delivery_time
     *
     * @param deliveryTime the value for act_print.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.finish_time
     *
     * @return the value of act_print.finish_time
     *
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.finish_time
     *
     * @param finishTime the value for act_print.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.create_by
     *
     * @return the value of act_print.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.create_by
     *
     * @param createBy the value for act_print.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.create_time
     *
     * @return the value of act_print.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.create_time
     *
     * @param createTime the value for act_print.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.update_by
     *
     * @return the value of act_print.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.update_by
     *
     * @param updateBy the value for act_print.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.update_time
     *
     * @return the value of act_print.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.update_time
     *
     * @param updateTime the value for act_print.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_print.remark
     *
     * @return the value of act_print.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_print.remark
     *
     * @param remark the value for act_print.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_print
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", printId=").append(printId);
        sb.append(", studentId=").append(studentId);
        sb.append(", fileName=").append(fileName);
        sb.append(", fileUrl=").append(fileUrl);
        sb.append(", userPrintId=").append(userPrintId);
        sb.append(", userDeliveryId=").append(userDeliveryId);
        sb.append(", printNumber=").append(printNumber);
        sb.append(", bothSideFlag=").append(bothSideFlag);
        sb.append(", colorFlag=").append(colorFlag);
        sb.append(", sealingFlag=").append(sealingFlag);
        sb.append(", coverFlag=").append(coverFlag);
        sb.append(", paperSize=").append(paperSize);
        sb.append(", studentRemark=").append(studentRemark);
        sb.append(", status=").append(status);
        sb.append(", addressId=").append(addressId);
        sb.append(", coverColor=").append(coverColor);
        sb.append(", fee=").append(fee);
        sb.append(", pageNum=").append(pageNum);
        sb.append(", payTime=").append(payTime);
        sb.append(", printTime=").append(printTime);
        sb.append(", deliveryTime=").append(deliveryTime);
        sb.append(", finishTime=").append(finishTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}