package com.example.lfm.entity;

import java.io.Serializable;
import java.util.Date;

public class PickUp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.pick_up_id
     *
     * @mbg.generated
     */
    private Long pickUpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.student_id
     *
     * @mbg.generated
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.take_code
     *
     * @mbg.generated
     */
    private String takeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.take_name
     *
     * @mbg.generated
     */
    private String takeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.takqe_address
     *
     * @mbg.generated
     */
    private String takqeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.take_phone
     *
     * @mbg.generated
     */
    private String takePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.user_pick_id
     *
     * @mbg.generated
     */
    private Long userPickId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.student_remark
     *
     * @mbg.generated
     */
    private String studentRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.address_id
     *
     * @mbg.generated
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.fee
     *
     * @mbg.generated
     */
    private Double fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.delivery_time
     *
     * @mbg.generated
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.cancel_time
     *
     * @mbg.generated
     */
    private Date cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pick_up.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pick_up
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.pick_up_id
     *
     * @return the value of pick_up.pick_up_id
     *
     * @mbg.generated
     */
    public Long getPickUpId() {
        return pickUpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.pick_up_id
     *
     * @param pickUpId the value for pick_up.pick_up_id
     *
     * @mbg.generated
     */
    public void setPickUpId(Long pickUpId) {
        this.pickUpId = pickUpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.student_id
     *
     * @return the value of pick_up.student_id
     *
     * @mbg.generated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.student_id
     *
     * @param studentId the value for pick_up.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.take_code
     *
     * @return the value of pick_up.take_code
     *
     * @mbg.generated
     */
    public String getTakeCode() {
        return takeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.take_code
     *
     * @param takeCode the value for pick_up.take_code
     *
     * @mbg.generated
     */
    public void setTakeCode(String takeCode) {
        this.takeCode = takeCode == null ? null : takeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.take_name
     *
     * @return the value of pick_up.take_name
     *
     * @mbg.generated
     */
    public String getTakeName() {
        return takeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.take_name
     *
     * @param takeName the value for pick_up.take_name
     *
     * @mbg.generated
     */
    public void setTakeName(String takeName) {
        this.takeName = takeName == null ? null : takeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.takqe_address
     *
     * @return the value of pick_up.takqe_address
     *
     * @mbg.generated
     */
    public String getTakqeAddress() {
        return takqeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.takqe_address
     *
     * @param takqeAddress the value for pick_up.takqe_address
     *
     * @mbg.generated
     */
    public void setTakqeAddress(String takqeAddress) {
        this.takqeAddress = takqeAddress == null ? null : takqeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.address
     *
     * @return the value of pick_up.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.address
     *
     * @param address the value for pick_up.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.status
     *
     * @return the value of pick_up.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.status
     *
     * @param status the value for pick_up.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.take_phone
     *
     * @return the value of pick_up.take_phone
     *
     * @mbg.generated
     */
    public String getTakePhone() {
        return takePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.take_phone
     *
     * @param takePhone the value for pick_up.take_phone
     *
     * @mbg.generated
     */
    public void setTakePhone(String takePhone) {
        this.takePhone = takePhone == null ? null : takePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.user_pick_id
     *
     * @return the value of pick_up.user_pick_id
     *
     * @mbg.generated
     */
    public Long getUserPickId() {
        return userPickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.user_pick_id
     *
     * @param userPickId the value for pick_up.user_pick_id
     *
     * @mbg.generated
     */
    public void setUserPickId(Long userPickId) {
        this.userPickId = userPickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.student_remark
     *
     * @return the value of pick_up.student_remark
     *
     * @mbg.generated
     */
    public String getStudentRemark() {
        return studentRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.student_remark
     *
     * @param studentRemark the value for pick_up.student_remark
     *
     * @mbg.generated
     */
    public void setStudentRemark(String studentRemark) {
        this.studentRemark = studentRemark == null ? null : studentRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.address_id
     *
     * @return the value of pick_up.address_id
     *
     * @mbg.generated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.address_id
     *
     * @param addressId the value for pick_up.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.fee
     *
     * @return the value of pick_up.fee
     *
     * @mbg.generated
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.fee
     *
     * @param fee the value for pick_up.fee
     *
     * @mbg.generated
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.pay_time
     *
     * @return the value of pick_up.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.pay_time
     *
     * @param payTime the value for pick_up.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.delivery_time
     *
     * @return the value of pick_up.delivery_time
     *
     * @mbg.generated
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.delivery_time
     *
     * @param deliveryTime the value for pick_up.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.finish_time
     *
     * @return the value of pick_up.finish_time
     *
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.finish_time
     *
     * @param finishTime the value for pick_up.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.cancel_time
     *
     * @return the value of pick_up.cancel_time
     *
     * @mbg.generated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.cancel_time
     *
     * @param cancelTime the value for pick_up.cancel_time
     *
     * @mbg.generated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.create_by
     *
     * @return the value of pick_up.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.create_by
     *
     * @param createBy the value for pick_up.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.create_time
     *
     * @return the value of pick_up.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.create_time
     *
     * @param createTime the value for pick_up.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.update_by
     *
     * @return the value of pick_up.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.update_by
     *
     * @param updateBy the value for pick_up.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.update_time
     *
     * @return the value of pick_up.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.update_time
     *
     * @param updateTime the value for pick_up.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.remark
     *
     * @return the value of pick_up.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.remark
     *
     * @param remark the value for pick_up.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pick_up.del_flag
     *
     * @return the value of pick_up.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pick_up.del_flag
     *
     * @param delFlag the value for pick_up.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pick_up
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pickUpId=").append(pickUpId);
        sb.append(", studentId=").append(studentId);
        sb.append(", takeCode=").append(takeCode);
        sb.append(", takeName=").append(takeName);
        sb.append(", takqeAddress=").append(takqeAddress);
        sb.append(", address=").append(address);
        sb.append(", status=").append(status);
        sb.append(", takePhone=").append(takePhone);
        sb.append(", userPickId=").append(userPickId);
        sb.append(", studentRemark=").append(studentRemark);
        sb.append(", addressId=").append(addressId);
        sb.append(", fee=").append(fee);
        sb.append(", payTime=").append(payTime);
        sb.append(", deliveryTime=").append(deliveryTime);
        sb.append(", finishTime=").append(finishTime);
        sb.append(", cancelTime=").append(cancelTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}