package com.example.lfm.entity;

import java.io.Serializable;
import java.util.Date;

public class SysFeedbackMedia implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.feedback_media_id
     *
     * @mbg.generated
     */
    private Long feedbackMediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.feedback_id
     *
     * @mbg.generated
     */
    private Long feedbackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.feedback_media_url
     *
     * @mbg.generated
     */
    private String feedbackMediaUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback_media.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_feedback_media
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.feedback_media_id
     *
     * @return the value of sys_feedback_media.feedback_media_id
     *
     * @mbg.generated
     */
    public Long getFeedbackMediaId() {
        return feedbackMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.feedback_media_id
     *
     * @param feedbackMediaId the value for sys_feedback_media.feedback_media_id
     *
     * @mbg.generated
     */
    public void setFeedbackMediaId(Long feedbackMediaId) {
        this.feedbackMediaId = feedbackMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.feedback_id
     *
     * @return the value of sys_feedback_media.feedback_id
     *
     * @mbg.generated
     */
    public Long getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.feedback_id
     *
     * @param feedbackId the value for sys_feedback_media.feedback_id
     *
     * @mbg.generated
     */
    public void setFeedbackId(Long feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.feedback_media_url
     *
     * @return the value of sys_feedback_media.feedback_media_url
     *
     * @mbg.generated
     */
    public String getFeedbackMediaUrl() {
        return feedbackMediaUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.feedback_media_url
     *
     * @param feedbackMediaUrl the value for sys_feedback_media.feedback_media_url
     *
     * @mbg.generated
     */
    public void setFeedbackMediaUrl(String feedbackMediaUrl) {
        this.feedbackMediaUrl = feedbackMediaUrl == null ? null : feedbackMediaUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.status
     *
     * @return the value of sys_feedback_media.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.status
     *
     * @param status the value for sys_feedback_media.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.create_by
     *
     * @return the value of sys_feedback_media.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.create_by
     *
     * @param createBy the value for sys_feedback_media.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.create_time
     *
     * @return the value of sys_feedback_media.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.create_time
     *
     * @param createTime the value for sys_feedback_media.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.update_by
     *
     * @return the value of sys_feedback_media.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.update_by
     *
     * @param updateBy the value for sys_feedback_media.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.update_time
     *
     * @return the value of sys_feedback_media.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.update_time
     *
     * @param updateTime the value for sys_feedback_media.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback_media.remark
     *
     * @return the value of sys_feedback_media.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback_media.remark
     *
     * @param remark the value for sys_feedback_media.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_feedback_media
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", feedbackMediaId=").append(feedbackMediaId);
        sb.append(", feedbackId=").append(feedbackId);
        sb.append(", feedbackMediaUrl=").append(feedbackMediaUrl);
        sb.append(", status=").append(status);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}