package com.example.lfm.entity;

import java.io.Serializable;
import java.util.Date;

public class SysFeedback implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.feedback_id
     *
     * @mbg.generated
     */
    private Long feedbackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.student_id
     *
     * @mbg.generated
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.feedback_content
     *
     * @mbg.generated
     */
    private String feedbackContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.user_manage_id
     *
     * @mbg.generated
     */
    private Long userManageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.manage_content
     *
     * @mbg.generated
     */
    private String manageContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_feedback.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_feedback
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.feedback_id
     *
     * @return the value of sys_feedback.feedback_id
     *
     * @mbg.generated
     */
    public Long getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.feedback_id
     *
     * @param feedbackId the value for sys_feedback.feedback_id
     *
     * @mbg.generated
     */
    public void setFeedbackId(Long feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.student_id
     *
     * @return the value of sys_feedback.student_id
     *
     * @mbg.generated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.student_id
     *
     * @param studentId the value for sys_feedback.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.feedback_content
     *
     * @return the value of sys_feedback.feedback_content
     *
     * @mbg.generated
     */
    public String getFeedbackContent() {
        return feedbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.feedback_content
     *
     * @param feedbackContent the value for sys_feedback.feedback_content
     *
     * @mbg.generated
     */
    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent == null ? null : feedbackContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.user_manage_id
     *
     * @return the value of sys_feedback.user_manage_id
     *
     * @mbg.generated
     */
    public Long getUserManageId() {
        return userManageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.user_manage_id
     *
     * @param userManageId the value for sys_feedback.user_manage_id
     *
     * @mbg.generated
     */
    public void setUserManageId(Long userManageId) {
        this.userManageId = userManageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.manage_content
     *
     * @return the value of sys_feedback.manage_content
     *
     * @mbg.generated
     */
    public String getManageContent() {
        return manageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.manage_content
     *
     * @param manageContent the value for sys_feedback.manage_content
     *
     * @mbg.generated
     */
    public void setManageContent(String manageContent) {
        this.manageContent = manageContent == null ? null : manageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.order_id
     *
     * @return the value of sys_feedback.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.order_id
     *
     * @param orderId the value for sys_feedback.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.order_type
     *
     * @return the value of sys_feedback.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.order_type
     *
     * @param orderType the value for sys_feedback.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.status
     *
     * @return the value of sys_feedback.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.status
     *
     * @param status the value for sys_feedback.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.del_flag
     *
     * @return the value of sys_feedback.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.del_flag
     *
     * @param delFlag the value for sys_feedback.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.create_by
     *
     * @return the value of sys_feedback.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.create_by
     *
     * @param createBy the value for sys_feedback.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.create_time
     *
     * @return the value of sys_feedback.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.create_time
     *
     * @param createTime the value for sys_feedback.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.update_by
     *
     * @return the value of sys_feedback.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.update_by
     *
     * @param updateBy the value for sys_feedback.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.update_time
     *
     * @return the value of sys_feedback.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.update_time
     *
     * @param updateTime the value for sys_feedback.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_feedback.remark
     *
     * @return the value of sys_feedback.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_feedback.remark
     *
     * @param remark the value for sys_feedback.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_feedback
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", feedbackId=").append(feedbackId);
        sb.append(", studentId=").append(studentId);
        sb.append(", feedbackContent=").append(feedbackContent);
        sb.append(", userManageId=").append(userManageId);
        sb.append(", manageContent=").append(manageContent);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderType=").append(orderType);
        sb.append(", status=").append(status);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}