package com.example.lfm.entity;

import java.io.Serializable;
import java.util.Date;

public class Washing implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.washing_id
     *
     * @mbg.generated
     */
    private Long washingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.student_id
     *
     * @mbg.generated
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.wash_type
     *
     * @mbg.generated
     */
    private String washType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.wash_address
     *
     * @mbg.generated
     */
    private String washAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.take_phone
     *
     * @mbg.generated
     */
    private String takePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.user_pick_id
     *
     * @mbg.generated
     */
    private Long userPickId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.student_remark
     *
     * @mbg.generated
     */
    private String studentRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.address_id
     *
     * @mbg.generated
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.fee
     *
     * @mbg.generated
     */
    private Double fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.delivery_time
     *
     * @mbg.generated
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.cancel_time
     *
     * @mbg.generated
     */
    private Date cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.del_flag
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column washing.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table washing
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.washing_id
     *
     * @return the value of washing.washing_id
     *
     * @mbg.generated
     */
    public Long getWashingId() {
        return washingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.washing_id
     *
     * @param washingId the value for washing.washing_id
     *
     * @mbg.generated
     */
    public void setWashingId(Long washingId) {
        this.washingId = washingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.student_id
     *
     * @return the value of washing.student_id
     *
     * @mbg.generated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.student_id
     *
     * @param studentId the value for washing.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.wash_type
     *
     * @return the value of washing.wash_type
     *
     * @mbg.generated
     */
    public String getWashType() {
        return washType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.wash_type
     *
     * @param washType the value for washing.wash_type
     *
     * @mbg.generated
     */
    public void setWashType(String washType) {
        this.washType = washType == null ? null : washType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.wash_address
     *
     * @return the value of washing.wash_address
     *
     * @mbg.generated
     */
    public String getWashAddress() {
        return washAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.wash_address
     *
     * @param washAddress the value for washing.wash_address
     *
     * @mbg.generated
     */
    public void setWashAddress(String washAddress) {
        this.washAddress = washAddress == null ? null : washAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.take_phone
     *
     * @return the value of washing.take_phone
     *
     * @mbg.generated
     */
    public String getTakePhone() {
        return takePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.take_phone
     *
     * @param takePhone the value for washing.take_phone
     *
     * @mbg.generated
     */
    public void setTakePhone(String takePhone) {
        this.takePhone = takePhone == null ? null : takePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.user_pick_id
     *
     * @return the value of washing.user_pick_id
     *
     * @mbg.generated
     */
    public Long getUserPickId() {
        return userPickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.user_pick_id
     *
     * @param userPickId the value for washing.user_pick_id
     *
     * @mbg.generated
     */
    public void setUserPickId(Long userPickId) {
        this.userPickId = userPickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.student_remark
     *
     * @return the value of washing.student_remark
     *
     * @mbg.generated
     */
    public String getStudentRemark() {
        return studentRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.student_remark
     *
     * @param studentRemark the value for washing.student_remark
     *
     * @mbg.generated
     */
    public void setStudentRemark(String studentRemark) {
        this.studentRemark = studentRemark == null ? null : studentRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.address_id
     *
     * @return the value of washing.address_id
     *
     * @mbg.generated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.address_id
     *
     * @param addressId the value for washing.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.fee
     *
     * @return the value of washing.fee
     *
     * @mbg.generated
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.fee
     *
     * @param fee the value for washing.fee
     *
     * @mbg.generated
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.pay_time
     *
     * @return the value of washing.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.pay_time
     *
     * @param payTime the value for washing.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.delivery_time
     *
     * @return the value of washing.delivery_time
     *
     * @mbg.generated
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.delivery_time
     *
     * @param deliveryTime the value for washing.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.finish_time
     *
     * @return the value of washing.finish_time
     *
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.finish_time
     *
     * @param finishTime the value for washing.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.cancel_time
     *
     * @return the value of washing.cancel_time
     *
     * @mbg.generated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.cancel_time
     *
     * @param cancelTime the value for washing.cancel_time
     *
     * @mbg.generated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.create_by
     *
     * @return the value of washing.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.create_by
     *
     * @param createBy the value for washing.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.create_time
     *
     * @return the value of washing.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.create_time
     *
     * @param createTime the value for washing.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.update_by
     *
     * @return the value of washing.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.update_by
     *
     * @param updateBy the value for washing.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.update_time
     *
     * @return the value of washing.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.update_time
     *
     * @param updateTime the value for washing.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.remark
     *
     * @return the value of washing.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.remark
     *
     * @param remark the value for washing.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.del_flag
     *
     * @return the value of washing.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.del_flag
     *
     * @param delFlag the value for washing.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column washing.status
     *
     * @return the value of washing.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column washing.status
     *
     * @param status the value for washing.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table washing
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", washingId=").append(washingId);
        sb.append(", studentId=").append(studentId);
        sb.append(", washType=").append(washType);
        sb.append(", washAddress=").append(washAddress);
        sb.append(", takePhone=").append(takePhone);
        sb.append(", userPickId=").append(userPickId);
        sb.append(", studentRemark=").append(studentRemark);
        sb.append(", addressId=").append(addressId);
        sb.append(", fee=").append(fee);
        sb.append(", payTime=").append(payTime);
        sb.append(", deliveryTime=").append(deliveryTime);
        sb.append(", finishTime=").append(finishTime);
        sb.append(", cancelTime=").append(cancelTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}