package com.example.lfm.dao;

import com.example.lfm.entity.F_FMedia;
import com.example.lfm.entity.FeedbackDetail;
import com.example.lfm.entity.SysFeedback;
import java.util.List;

public interface SysFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_feedback
     *
     * @mbg.generated
     */
    Long insert(SysFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_feedback
     *
     * @mbg.generated
     */
    SysFeedback selectByPrimaryKey(Long feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_feedback
     *
     * @mbg.generated
     */
    List<SysFeedback> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysFeedback record);


    List<FeedbackDetail> selectByStudentId(Long studentId);
}