package com.example.lfm.dao;

import com.example.lfm.entity.SysRoleSchool;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_school
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleId") Long roleId, @Param("schoolId") Long schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_school
     *
     * @mbg.generated
     */
    int insert(SysRoleSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_school
     *
     * @mbg.generated
     */
    List<SysRoleSchool> selectAll();
}