package com.example.lfm.dao;

import com.example.lfm.entity.SysSchool;

import java.util.List;

public interface SysSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_school
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_school
     *
     * @mbg.generated
     */
    int insert(SysSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_school
     *
     * @mbg.generated
     */
    SysSchool selectByPrimaryKey(Long schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_school
     *
     * @mbg.generated
     */
    List<SysSchool> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_school
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysSchool record);
}