package com.example.lfm.dao;

import com.example.lfm.entity.Washing;
import java.util.List;

public interface WashingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table washing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long washingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table washing
     *
     * @mbg.generated
     */
    int insert(Washing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table washing
     *
     * @mbg.generated
     */
    Washing selectByPrimaryKey(Long washingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table washing
     *
     * @mbg.generated
     */
    List<Washing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table washing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Washing record);
}